module.exports = {
  UserController: require('./user'),
  BarController: require('./bar'),
  BreweryController: require('./brewery'),
  TypeOfBeerController: require('./typeOfBeer'),
  BeerController: require('./beer'),
  CommentsBeerController: require('./commentsBeer'),
  CommentsBarController: require('./commentsBar'),
  CommentsBreweryController: require('./commentsBrewery'),
  NotesBeerController: require('./notesBeer'),
  NotesBarController: require('./notesBar'),
  NotesBreweryController: require('./notesBrewery'),
  PicturesBarController: require('./picturesBar'),
  PicturesBreweryController: require('./picturesBrewery'),
  MenusBeerController: require('./menusBeer'),
  ReservationController: require('./reservation'),
  OrderMenuBeerController: require('./orderMenuBeer'),
  EventController: require('./event'),
  OpeningHourController: require('./openingHour'),
  FriendController: require('./friend'),
  GroupController: require('./group'),
  MessageController: require('./message')
}
